[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERBOSE = "true"
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
