[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
replicas = 1

[environments.production]
APP_ENV = "production"
APP_DEBUG = "false"